spring.datasource.url=jdbc:mysql://localhost:3306/dummydb
spring.datasource.username=admin
spring.datasource.password=uuid_b67f19b3355849cf9d710f900d4cc390
api.key=uuid_1845122feb7d402694277be63cb601fd
